# Generated by Django 5.2.5 on 2025-08-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('blog', 'Blog/Website'), ('research', 'Research Paper'), ('thesis', 'Thesis')], max_length=20)),
                ('price_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_borrow', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='accounts.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_year', models.PositiveIntegerField()),
                ('volume_number', models.PositiveIntegerField(default=1)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='contents.content')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_details', to='contents.content')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaperDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_details', to='contents.content')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_details', to='contents.content')),
            ],
        ),
    ]
